
# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
jobs:
  test-project:
    docker:
      # specify the version you desire here
      - image: clojure:lein-2.7.1

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/lein-git-info

    environment:
      LEIN_ROOT: "true"
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx2048m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "project.clj" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
        name: download dependencies
        command: lein deps

      # run tests!
      - run:
        name: code cover test
        command: lein cloverage --codecov

      - run:
        name: codecov report
        command: bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "project.clj" }}

      - store_artifacts:
          path: target/coverage

workflows:
  version: 2
  run_all_tests:
    jobs:
      - test-project
